version: '2'
volumes:
  settings:
  browser-settings:
  audio:                          # Required for PA over UNIX socket
  zerotier-data:
  tailscale-data:

services:
  audio:
    image: balenaplayground/balenalabs-audio:intel-nuc
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
#     io.balena.features.kernel-modules: '1'
#     io.balena.features.procfs: '1'
#     io.balena.features.sysfs: '1'
    volumes:
      - 'audio:/run/pulse'
    ports:
      - 4317:4317
    environment:
      AUDIO_OUTPUT: 'RPI_HEADPHONES'
      DBUS_SYSTEM_BUS_ADDRESS: 'unix:path=/host/run/dbus/system_bus_socket'
  balenalabs-browser:
    build: ./balenalabs-browser
    privileged: true
    network_mode: host
    restart: always
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
      io.balena.features.kernel-modules: '1'
    ports:
      - 5012:5012
      - 35173:35173
    volumes:
      - 'browser-settings:/data'
    environment:
      LAUNCH_URL: 'https://localhost'
      LOCAL_HTTP_DELAY: '10'
      API_PORT: '5012'
      SHOW_CURSOR: '0'
      REMOTE_DEBUG_PORT: '35173'
      WINDOW_SIZE: '1920,1080'
      ENABLE_GPU: '1'
      KIOSK: '1'
      PERSISTENT: '1'
      DBUS_SYSTEM_BUS_ADDRESS: 'unix:path=/host/run/dbus/system_bus_socket'
    depends_on:
      - lighttpd
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
  tailscale:
#    # privileged may be optional, but requires manual step in that case
#    # https://github.com/tailscale/tailscale/issues/504
    privileged: true
    restart: no
    build:
     context: ./tailscale
     dockerfile: Dockerfile.template
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    network_mode: host
    volumes:
      - tailscale-data:/tailscale
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
    environment:
      TAILSCALE_AUTHKEY: 'tskey-auth-kDm37D1CNTRL-23tm6sKnHFEkh1hFBBfcEEZmByiy3gysY'
      TAILSCALE_APIKEY: 'tskey-api-kxeN6h2CNTRL-6LcA2fMf7eaCEBSecymXdaYPk31mVyTb'
      DBUS_SYSTEM_BUS_ADDRESS: 'unix:path=/host/run/dbus/system_bus_socket'
  lighttpd:
    build: ./lighttpd
    restart: always
    privileged: true
    ports:
      - 80:80
      - 443:443
#   depends_on:
#     - tailscale  
  zerotier:
    # This volume is needed to make ZT configuration survive a reboot and new container version
    volumes:
      - zerotier-data:/var/lib/zerotier-one
    build:
      context: ./balena-zerotier
    # privileged is needed for ZeroTier to avoid "cannot bind to local control interface port" error
    privileged: true
    network_mode: host
    # SYS_ADMIN is needed because NET_ADMIN does not include the ioctl() required to put /dev/net/tun in tap mode.
    # Source : https://zerotier.atlassian.net/wiki/spaces/SD/pages/7536656/Running+ZeroTier+in+a+Docker+Container
    # NET_ADMIN is also needed to avoid "zerotier-one: fatal error: cannot bind to local control interface port" error
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    # Enable dbus communications for nmcli commands
    # Source : https://github.com/balena-io/wifi-connect
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: 'unix:path=/host/run/dbus/system_bus_socket'
