version: '2'
volumes:
  settings:
  pulse:                          # Required for PA over UNIX socket
  weston:
services:
  audio:
    image: balenablocks/audio
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
    volumes:
      - 'pulse:/run/pulse'
  weston:
    restart: always
    image: igalia/balena-weston:raspberrypi3-64
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
    volumes:
      - 'weston:/run/weston'
  wpe:
    restart: always
    build: ./browser-wpe
    privileged: true
    ports:
      - 8080:8080
      - 12321:12321
    volumes:
      - 'weston:/run/weston'
      - 'pulse:/run/pulse'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
  wifi-connect:
    build: ./wifi-connect
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  fbcp:
    build: ./fbcp
    restart: on-failure
    privileged: true
  lighttpd:
    build: ./lighttpd
    restart: always
    privileged: true
    ports:
      - 80:80
      - 443:443